import React, { useState } from 'react';
import { useStudio } from '../store/useStudio.js';
import { exportToWebM, downloadBlob } from '../utils/canvasExport.js';

export default function ExportPanel() {
  const { template } = useStudio();
  const [videoProgress, setVideoProgress] = useState(null); // null | 0-1
  const [error, setError] = useState('');

  // ── JSON export (no backend needed) ──────────────────────────────────────
  const exportJSON = () => {
    const json = JSON.stringify(template, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    downloadBlob(blob, `${template.name || 'template'}.json`);
  };

  // ── WebM/MP4 export via MediaRecorder (no backend needed) ─────────────────
  const exportVideo = async () => {
    setError('');
    setVideoProgress(0);
    try {
      const blob = await exportToWebM(template, p => setVideoProgress(p));
      downloadBlob(blob, `${template.name || 'animation'}.webm`);
    } catch (e) {
      setError(e.message || 'Export failed');
    } finally {
      setVideoProgress(null);
    }
  };

  // ── After Effects JSX (client-side) ──────────────────────────────────────
  const exportAEScript = () => {
    const lines = [
      `// After Effects Script — ${template.name}`,
      `// Generated by Motion Studio`,
      `var comp = app.project.items.addComp("${template.name}", ${template.width}, ${template.height}, 1, ${template.duration}, ${template.fps});`,
      '',
    ];
    template.layers.forEach((layer, i) => {
      const p = layer.properties;
      if (layer.type === 'text') {
        lines.push(`var tl${i} = comp.layers.addText("${(p.text || '').replace(/\n/g, '\\n').replace(/"/g, '\\"')}");`);
        lines.push(`tl${i}.name = "${layer.name}";`);
      } else {
        lines.push(`var sl${i} = comp.layers.addShape(); sl${i}.name = "${layer.name}";`);
      }
    });
    lines.push('alert("Layers created! Position/keyframe data — see Motion Studio JSON export.");');
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    downloadBlob(blob, `${template.name || 'template'}.jsx`);
  };

  return (
    <div className="p-4 flex flex-col gap-4 overflow-y-auto h-full">
      <div className="text-xs font-semibold text-studio-muted uppercase tracking-wider">Export</div>

      <ExportCard
        title="JSON Template"
        desc="Download the raw template JSON. Reimportable and editable."
        icon="{ }"
        badge="Instant"
        onClick={exportJSON}
      />

      <ExportCard
        title="WebM Video"
        desc="Renders all frames locally in your browser — no server needed."
        icon="▶"
        badge="Client-side"
        loading={videoProgress !== null}
        progress={videoProgress}
        onClick={exportVideo}
      />

      <ExportCard
        title="After Effects Script"
        desc="JSX script to recreate layers in Adobe After Effects."
        icon="Ae"
        badge="JSX"
        onClick={exportAEScript}
      />

      {error && <div className="text-xs text-red-400 bg-red-900/20 rounded p-2">{error}</div>}

      <div className="border-t border-studio-border pt-4 flex flex-col gap-1 text-xs text-studio-muted">
        <Row label="Name" value={template.name} />
        <Row label="Size" value={`${template.width} × ${template.height}`} />
        <Row label="Duration" value={`${template.duration}s @ ${template.fps}fps`} />
        <Row label="Layers" value={template.layers.length} />
      </div>
    </div>
  );
}

function ExportCard({ title, desc, icon, badge, loading, progress, onClick }) {
  return (
    <button
      className="flex items-start gap-3 p-3 rounded border border-studio-border bg-studio-bg
        hover:border-studio-accent/50 hover:bg-studio-accent/5 transition-colors text-left w-full disabled:opacity-60"
      onClick={onClick}
      disabled={loading}
    >
      <div className="w-10 h-10 rounded bg-studio-panel flex items-center justify-center text-sm font-mono flex-shrink-0">
        {loading
          ? <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
          : icon}
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <span className="text-sm font-medium text-studio-text">{title}</span>
          {badge && <span className="text-[10px] bg-studio-accent/20 text-studio-accent rounded px-1.5 py-0.5">{badge}</span>}
        </div>
        <div className="text-xs text-studio-muted mt-0.5">{desc}</div>
        {loading && progress !== null && (
          <div className="mt-2 h-1 bg-studio-border rounded-full overflow-hidden">
            <div className="h-full bg-studio-accent rounded-full transition-all" style={{ width: `${Math.round(progress * 100)}%` }} />
          </div>
        )}
      </div>
    </button>
  );
}

function Row({ label, value }) {
  return (
    <div className="flex justify-between">
      <span>{label}</span>
      <span className="text-studio-text">{value}</span>
    </div>
  );
}
